# Documentation

pymupdf

This notebook demonstrates how to extract transaction data from a PDF bank statement, clean it, and transform it into a standardized JSON format. Below is a breakdown of each step:

In [ ]:
https://pypi.org/project/pdfplumber/

# Installation

pdfplumber: A Python library for extracting text and tables from PDFs.This works best on machine-generated, rather than scanned PDFs

pandas: Used for data manipulation and transformation.

Installs required libraries:

In [ ]:
!pip install pdfplumber
!pip install pandas

Collecting pdfplumber
  Downloading pdfplumber-0.11.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.4 MB/s eta 0:00:00
Collecting pdfminer.six==20250327 (from pdfplumber)
  Downloading pdfminer_six-20250327-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.1.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.1)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)
Downloading pdfplumber-0.11.6-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.2/60.2 kB 2.7 MB/s eta 0:00:00
Downloading pdfminer_six-20250327-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 26.9 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 38.0 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250327 pdfplumber-0.11.6 pypdfium2-4.30.1
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# EXPECTED FORMAT

The goal is to structure transactions into a JSON array of objects with fields:
`id`, `type`, `amount`, `narration`, `date`, `balance`.

Example:



```
[
  {
    "id": "0",
    "type": "credit",
    "amount": 17880,
    "narration": "Fixed Deposit Closure Proceeds - Principal",
    "date": "2020-05-18T00:00:00",
    "balance": 18170
  },
  {
    "id": "0",
    "type": "debit",
    "amount": 17880,
    "narration": "ALAT NIP TRANSFER TO POLARIS-tithe",
    "date": "2020-05-18T00:00:00",
    "balance": 290
  },
  {
    "id": "0",
    "type": "debit",
    "amount": 25,
    "narration": "COMM ALAT NIP TRANSFER TO POLARIS-tithe",
    "date": "2020-05-18T00:00:00",
    "balance": 265
  }
]
```

# IMPORTS

In [ ]:
import pdfplumber
import pandas as pd

# FUNCTION TO EXTRACT

You can find table extraction guild following this link: ` https://github.com/jsvine/pdfplumber`

In [ ]:
def extract_and_concat_tables_from_pdf(pdf_path):
    """
    Extracts tables from a PDF using pdfplumber and concatenates them into a single Pandas DataFrame.

    Args:
        pdf_path (str): Path to the PDF file.

    Returns:
        pd.DataFrame: A single concatenated DataFrame containing all extracted tables.
    """
    tables = []  # List to store extracted tables
    with pdfplumber.open(pdf_path) as pdf:
        for page_number, page in enumerate(pdf.pages, start=1):
            print(f"Processing page {page_number}...")
            page_tables = page.extract_tables(
                {
                "vertical_strategy": "lines",  # Use lines to detect vertical separators
                "horizontal_strategy": "lines",  # Use lines to detect horizontal separators
                "intersection_tolerance": 5,  # Adjust sensitivity
                }


            )  # Extract tables from the page
            for table in page_tables:
                # Convert the table to a Pandas DataFrame
                df = pd.DataFrame(table)
                tables.append(df)

    # Concatenate all DataFrames into a single DataFrame
    if tables:
        concatenated_df = pd.concat(tables, ignore_index=True)
        return concatenated_df
    else:
        print("No tables were found in the PDF.")
        return pd.DataFrame()

LOADING THE PDF

In [ ]:
pdf_path = '/content/your_bank_statement.pdf'
gtb = extract_and_concat_tables_from_pdf(pdf_path)

CHECK THE EXTRACTED DATA

In [ ]:
gtb.head(50)

START THE CLEANING PROCESS

---

# EXAMPLE 1- ALAT

In [ ]:
pdf_path = '/content/27052020115935_Statement_For_OLUWASOGO OGUNDOWOLE_0234952225_9993 (1).pdf'
alat = extract_and_concat_tables_from_pdf(pdf_path)

WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox
WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox
WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox

Processing page 1...
Processing page 2...

WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox
WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox
WARNING:pdfminer.pdfpage:CropBox missing from /Page, defaulting to MediaBox

Processing page 3...

In [ ]:
alat

,0,1,2,3,4,5,6
0,DATE,REFERENCE NUMBER,TRANSACTION DETAILS,Debit,Credit,Balance,NaN
1,18-May-2020,M4439,Fixed Deposit Closure Proceeds - Principal,,"17,880.00","18,170.48",NaN
2,18-May-2020,S5741873,ALAT NIP TRANSFER TO POLARIS-tithe,"17,880.00",,290.48,NaN
3,18-May-2020,S5741873,COMM ALAT NIP TRANSFER TO POLARIS-tithe,25.00,,265.48,NaN
4,18-May-2020,S5741873,VAT ALAT NIP TRANSFER TO POLARIS-tithe,1.88,,263.60,NaN
5,18-May-2020,S6493060,Wema USSD Transfer from BOLU JOHNSON OGUNDOW,,"6,000.00","6,263.60",NaN
6,18-May-2020,S6689372,ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASOGO O,"6,000.00",,263.60,NaN
7,18-May-2020,S6689372,COMM ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWAS,25.00,,238.60,NaN
8,18-May-2020,S6689372,VAT ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASO,1.88,,236.72,NaN
9,18-May-2020,S6741605,NIP:OLUWASOGO OGUNDOWOLE-INVISIBLE TECHNOLOGIES,,"190,395.12","190,631.84",NaN
10,18-May-2020,S6763049,NIP:OGUNDOWOLE OLUWASOGO OLUWAFE-,,"5,000.00","195,631.84",NaN
11,18-May-2020,S6771047,STAMP DUTY ON 1 TRANS : 18-MAY-20,50.00,,"195,581.84",NaN
12,19-May-2020,M3602,Initial Deposit for 0703873550,"29,000.00",,"166,581.84",NaN
13,19-May-2020,S6809232,ALAT TRANSFER TO OLAYEMI AFOLARI,"7,000.00",,"159,581.84",NaN
14,   www.alat.ng\n0700 CALL ALAT (0700234874),None,None,None,None,None,NaN
15,19-May-2020,S6809860,ALAT NIP TRANSFER TO PROVIDUS-,"15,000.00",,"144,581.84",
16,19-May-2020,S6809860,COMM ALAT NIP TRANSFER TO PROVIDUS-,25.00,,"144,556.84",None
17,19-May-2020,S6809860,VAT ALAT NIP TRANSFER TO PROVIDUS-,1.88,,"144,554.96",None
18,19-May-2020,S6810159,ALAT NIP TRANSFER TO FBN-,"100,000.00",,"44,554.96",None
19,19-May-2020,S6810159,COMM ALAT NIP TRANSFER TO FBN-,50.00,,"44,504.96",None
20,19-May-2020,S6810159,VAT ALAT NIP TRANSFER TO FBN-,3.75,,"44,501.21",None
21,19-May-2020,S6811109,ALAT NIP TRANSFER TO GTB-,"25,000.00",,"19,501.21",None
22,19-May-2020,S6811109,COMM ALAT NIP TRANSFER TO GTB-,25.00,,"19,476.21",None
23,19-May-2020,S6811109,VAT ALAT NIP TRANSFER TO GTB-,1.88,,"19,474.33",None
24,19-May-2020,S6812560,ALAT NIP TRANSFER TO GTB-Junefirst,"10,000.00",,"9,474.33",None
25,19-May-2020,S6812560,COMM ALAT NIP TRANSFER TO GTB-Junefirst,25.00,,"9,449.33",None
26,19-May-2020,S6812560,VAT ALAT NIP TRANSFER TO GTB-Junefirst,1.88,,"9,447.45",None
27,19-May-2020,S6832754,ALAT NIP TRANSFER TO GTB-order,"2,600.00",,"6,847.45",None
28,19-May-2020,S6832754,COMM ALAT NIP TRANSFER TO GTB-order,10.00,,"6,837.45",None
29,19-May-2020,S6832754,VAT ALAT NIP TRANSFER TO GTB-order,0.75,,"6,836.70",None
30,20-May-2020,S7478159,ALAT NIP TRANSFER TO GTB-,"2,000.00",,"4,836.70",None
31,20-May-2020,S7478159,COMM ALAT NIP TRANSFER TO GTB-,10.00,,"4,826.70",None
32,   www.alat.ng\n0700 CALL ALAT (0700234874),None,None,None,None,None,None
33,20-May-2020,S7478159,VAT ALAT NIP TRANSFER TO GTB-,0.75,,"4,825.95",
34,27-May-2020,S9904627,Wema USSD Transfer from OLAYEMI AFOLARIN OYE,,"7,000.00","11,825.95",None
35,27-May-2020,S9949826,Wema USSD Transfer from BOLU JOHNSON OGUNDOW,,"20,000.00","31,825.95",None

## Rename the columns properly

In [ ]:
alat.columns = ["Date", "Reference Number", "Transaction Details", "Debit", "Credit", "Balance", "Extra Column"]

## Drop the Extra Column

In [ ]:
alat = alat.drop(columns=["Extra Column"])

## drop columns where all the rows are null and reset index

In [ ]:
alat = alat.dropna(subset=["Transaction Details", "Debit", "Credit"], how="all")

alat = alat[1:].reset_index(drop=True)

In [ ]:
alat

,Date,Reference Number,Transaction Details,Debit,Credit,Balance
0,18-May-2020,M4439,Fixed Deposit Closure Proceeds - Principal,,"17,880.00","18,170.48"
1,18-May-2020,S5741873,ALAT NIP TRANSFER TO POLARIS-tithe,"17,880.00",,290.48
2,18-May-2020,S5741873,COMM ALAT NIP TRANSFER TO POLARIS-tithe,25.00,,265.48
3,18-May-2020,S5741873,VAT ALAT NIP TRANSFER TO POLARIS-tithe,1.88,,263.60
4,18-May-2020,S6493060,Wema USSD Transfer from BOLU JOHNSON OGUNDOW,,"6,000.00","6,263.60"
5,18-May-2020,S6689372,ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASOGO O,"6,000.00",,263.60
6,18-May-2020,S6689372,COMM ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWAS,25.00,,238.60
7,18-May-2020,S6689372,VAT ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASO,1.88,,236.72
8,18-May-2020,S6741605,NIP:OLUWASOGO OGUNDOWOLE-INVISIBLE TECHNOLOGIES,,"190,395.12","190,631.84"
9,18-May-2020,S6763049,NIP:OGUNDOWOLE OLUWASOGO OLUWAFE-,,"5,000.00","195,631.84"
10,18-May-2020,S6771047,STAMP DUTY ON 1 TRANS : 18-MAY-20,50.00,,"195,581.84"
11,19-May-2020,M3602,Initial Deposit for 0703873550,"29,000.00",,"166,581.84"
12,19-May-2020,S6809232,ALAT TRANSFER TO OLAYEMI AFOLARI,"7,000.00",,"159,581.84"
13,19-May-2020,S6809860,ALAT NIP TRANSFER TO PROVIDUS-,"15,000.00",,"144,581.84"
14,19-May-2020,S6809860,COMM ALAT NIP TRANSFER TO PROVIDUS-,25.00,,"144,556.84"
15,19-May-2020,S6809860,VAT ALAT NIP TRANSFER TO PROVIDUS-,1.88,,"144,554.96"
16,19-May-2020,S6810159,ALAT NIP TRANSFER TO FBN-,"100,000.00",,"44,554.96"
17,19-May-2020,S6810159,COMM ALAT NIP TRANSFER TO FBN-,50.00,,"44,504.96"
18,19-May-2020,S6810159,VAT ALAT NIP TRANSFER TO FBN-,3.75,,"44,501.21"
19,19-May-2020,S6811109,ALAT NIP TRANSFER TO GTB-,"25,000.00",,"19,501.21"
20,19-May-2020,S6811109,COMM ALAT NIP TRANSFER TO GTB-,25.00,,"19,476.21"
21,19-May-2020,S6811109,VAT ALAT NIP TRANSFER TO GTB-,1.88,,"19,474.33"
22,19-May-2020,S6812560,ALAT NIP TRANSFER TO GTB-Junefirst,"10,000.00",,"9,474.33"
23,19-May-2020,S6812560,COMM ALAT NIP TRANSFER TO GTB-Junefirst,25.00,,"9,449.33"
24,19-May-2020,S6812560,VAT ALAT NIP TRANSFER TO GTB-Junefirst,1.88,,"9,447.45"
25,19-May-2020,S6832754,ALAT NIP TRANSFER TO GTB-order,"2,600.00",,"6,847.45"
26,19-May-2020,S6832754,COMM ALAT NIP TRANSFER TO GTB-order,10.00,,"6,837.45"
27,19-May-2020,S6832754,VAT ALAT NIP TRANSFER TO GTB-order,0.75,,"6,836.70"
28,20-May-2020,S7478159,ALAT NIP TRANSFER TO GTB-,"2,000.00",,"4,836.70"
29,20-May-2020,S7478159,COMM ALAT NIP TRANSFER TO GTB-,10.00,,"4,826.70"
30,20-May-2020,S7478159,VAT ALAT NIP TRANSFER TO GTB-,0.75,,"4,825.95"
31,27-May-2020,S9904627,Wema USSD Transfer from OLAYEMI AFOLARIN OYE,,"7,000.00","11,825.95"
32,27-May-2020,S9949826,Wema USSD Transfer from BOLU JOHNSON OGUNDOW,,"20,000.00","31,825.95"

## CHANGE DATE TO THE NEEDED FORMAT

In [ ]:
alat["Date"] = pd.to_datetime(alat["Date"], format="%d-%b-%Y", errors="coerce").dt.strftime("%Y-%m-%d")

## CHANGE THE FIGURES TO THE NEEDED FORMAT

In [ ]:
alat["Debit"] = alat["Debit"].replace({",": "", "":0}, regex=True).astype(float).astype(int)
alat["Credit"] = alat["Credit"].replace({",": "", "":0}, regex=True).astype(float).astype(int)
alat["Balance"] = alat["Balance"].replace({",": "", "":0}, regex=True).astype(float).astype(int)

## TRANSFORM THE ROW TO THE REQUIRED FORMAT

In [ ]:
import re

def transform_row_alat(row):
    return {
        "id": "0",
        "type": "debit" if int(row["Debit"]) > 0 else "credit",
        "amount": row["Debit"] if int(row["Debit"]) > 0 else row["Credit"],
        "narration": row["Transaction Details"].replace(r"'", ""),
        "date": row["Date"]+ "T00:00:00",
        "balance": row["Balance"] 
    }
transformed_alat = alat.apply(transform_row_alat, axis=1).tolist()
transformed_alat_df = pd.DataFrame(transformed_alat)
transformed_alat_df.head(30)

,id,type,amount,narration,date,balance
0,4439,credit,17880,Fixed Deposit Closure Proceeds - Principal,2020-05-18T00:00:00,18170
1,5741873,debit,17880,ALAT NIP TRANSFER TO POLARIS-tithe,2020-05-18T00:00:00,290
2,5741873,debit,25,COMM ALAT NIP TRANSFER TO POLARIS-tithe,2020-05-18T00:00:00,265
3,5741873,debit,1,VAT ALAT NIP TRANSFER TO POLARIS-tithe,2020-05-18T00:00:00,263
4,6493060,credit,6000,Wema USSD Transfer from BOLU JOHNSON OGUNDOW,2020-05-18T00:00:00,6263
5,6689372,debit,6000,ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASOGO O,2020-05-18T00:00:00,263
6,6689372,debit,25,COMM ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWAS,2020-05-18T00:00:00,238
7,6689372,debit,1,VAT ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASO,2020-05-18T00:00:00,236
8,6741605,credit,190395,NIP:OLUWASOGO OGUNDOWOLE-INVISIBLE TECHNOLOGIES,2020-05-18T00:00:00,190631
9,6763049,credit,5000,NIP:OGUNDOWOLE OLUWASOGO OLUWAFE-,2020-05-18T00:00:00,195631
10,6771047,debit,50,STAMP DUTY ON 1 TRANS : 18-MAY-20,2020-05-18T00:00:00,195581
11,3602,debit,29000,Initial Deposit for 0703873550,2020-05-19T00:00:00,166581
12,6809232,debit,7000,ALAT TRANSFER TO OLAYEMI AFOLARI,2020-05-19T00:00:00,159581
13,6809860,debit,15000,ALAT NIP TRANSFER TO PROVIDUS-,2020-05-19T00:00:00,144581
14,6809860,debit,25,COMM ALAT NIP TRANSFER TO PROVIDUS-,2020-05-19T00:00:00,144556
15,6809860,debit,1,VAT ALAT NIP TRANSFER TO PROVIDUS-,2020-05-19T00:00:00,144554
16,6810159,debit,100000,ALAT NIP TRANSFER TO FBN-,2020-05-19T00:00:00,44554
17,6810159,debit,50,COMM ALAT NIP TRANSFER TO FBN-,2020-05-19T00:00:00,44504
18,6810159,debit,3,VAT ALAT NIP TRANSFER TO FBN-,2020-05-19T00:00:00,44501
19,6811109,debit,25000,ALAT NIP TRANSFER TO GTB-,2020-05-19T00:00:00,19501
20,6811109,debit,25,COMM ALAT NIP TRANSFER TO GTB-,2020-05-19T00:00:00,19476
21,6811109,debit,1,VAT ALAT NIP TRANSFER TO GTB-,2020-05-19T00:00:00,19474
22,6812560,debit,10000,ALAT NIP TRANSFER TO GTB-Junefirst,2020-05-19T00:00:00,9474
23,6812560,debit,25,COMM ALAT NIP TRANSFER TO GTB-Junefirst,2020-05-19T00:00:00,9449
24,6812560,debit,1,VAT ALAT NIP TRANSFER TO GTB-Junefirst,2020-05-19T00:00:00,9447
25,6832754,debit,2600,ALAT NIP TRANSFER TO GTB-order,2020-05-19T00:00:00,6847
26,6832754,debit,10,COMM ALAT NIP TRANSFER TO GTB-order,2020-05-19T00:00:00,6837
27,6832754,credit,0,VAT ALAT NIP TRANSFER TO GTB-order,2020-05-19T00:00:00,6836
28,7478159,debit,2000,ALAT NIP TRANSFER TO GTB-,2020-05-20T00:00:00,4836
29,7478159,debit,10,COMM ALAT NIP TRANSFER TO GTB-,2020-05-20T00:00:00,4826

## EXPORT AS JSON

In [ ]:
transformed_alat_df.to_json(orient="records")

'[{"id":"4439","type":"credit","amount":17880,"narration":"Fixed Deposit Closure Proceeds - Principal","date":"2020-05-18T00:00:00","balance":18170},{"id":"5741873","type":"debit","amount":17880,"narration":"ALAT NIP TRANSFER TO POLARIS-tithe","date":"2020-05-18T00:00:00","balance":290},{"id":"5741873","type":"debit","amount":25,"narration":"COMM ALAT NIP TRANSFER TO POLARIS-tithe","date":"2020-05-18T00:00:00","balance":265},{"id":"5741873","type":"debit","amount":1,"narration":"VAT ALAT NIP TRANSFER TO POLARIS-tithe","date":"2020-05-18T00:00:00","balance":263},{"id":"6493060","type":"credit","amount":6000,"narration":"Wema USSD Transfer from BOLU JOHNSON OGUNDOW","date":"2020-05-18T00:00:00","balance":6263},{"id":"6689372","type":"debit","amount":6000,"narration":"ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASOGO O","date":"2020-05-18T00:00:00","balance":263},{"id":"6689372","type":"debit","amount":25,"narration":"COMM ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWAS","date":"2020-05-18T00:00:00","balance":238},{"id":"6689372","type":"debit","amount":1,"narration":"VAT ALAT NIP TRANSFER TO GTB-OGUNDOWOLE OLUWASO","date":"2020-05-18T00:00:00","balance":236},{"id":"6741605","type":"credit","amount":190395,"narration":"NIP:OLUWASOGO OGUNDOWOLE-INVISIBLE TECHNOLOGIES","date":"2020-05-18T00:00:00","balance":190631},{"id":"6763049","type":"credit","amount":5000,"narration":"NIP:OGUNDOWOLE OLUWASOGO OLUWAFE-","date":"2020-05-18T00:00:00","balance":195631},{"id":"6771047","type":"debit","amount":50,"narration":"STAMP DUTY ON 1 TRANS : 18-MAY-20","date":"2020-05-18T00:00:00","balance":195581},{"id":"3602","type":"debit","amount":29000,"narration":"Initial Deposit for 0703873550","date":"2020-05-19T00:00:00","balance":166581},{"id":"6809232","type":"debit","amount":7000,"narration":"ALAT TRANSFER TO OLAYEMI AFOLARI","date":"2020-05-19T00:00:00","balance":159581},{"id":"6809860","type":"debit","amount":15000,"narration":"ALAT NIP TRANSFER TO PROVIDUS-","date":"2020-05-19T00:00:00","balance":144581},{"id":"6809860","type":"debit","amount":25,"narration":"COMM ALAT NIP TRANSFER TO PROVIDUS-","date":"2020-05-19T00:00:00","balance":144556},{"id":"6809860","type":"debit","amount":1,"narration":"VAT ALAT NIP TRANSFER TO PROVIDUS-","date":"2020-05-19T00:00:00","balance":144554},{"id":"6810159","type":"debit","amount":100000,"narration":"ALAT NIP TRANSFER TO FBN-","date":"2020-05-19T00:00:00","balance":44554},{"id":"6810159","type":"debit","amount":50,"narration":"COMM ALAT NIP TRANSFER TO FBN-","date":"2020-05-19T00:00:00","balance":44504},{"id":"6810159","type":"debit","amount":3,"narration":"VAT ALAT NIP TRANSFER TO FBN-","date":"2020-05-19T00:00:00","balance":44501},{"id":"6811109","type":"debit","amount":25000,"narration":"ALAT NIP TRANSFER TO GTB-","date":"2020-05-19T00:00:00","balance":19501},{"id":"6811109","type":"debit","amount":25,"narration":"COMM ALAT NIP TRANSFER TO GTB-","date":"2020-05-19T00:00:00","balance":19476},{"id":"6811109","type":"debit","amount":1,"narration":"VAT ALAT NIP TRANSFER TO GTB-","date":"2020-05-19T00:00:00","balance":19474},{"id":"6812560","type":"debit","amount":10000,"narration":"ALAT NIP TRANSFER TO GTB-Junefirst","date":"2020-05-19T00:00:00","balance":9474},{"id":"6812560","type":"debit","amount":25,"narration":"COMM ALAT NIP TRANSFER TO GTB-Junefirst","date":"2020-05-19T00:00:00","balance":9449},{"id":"6812560","type":"debit","amount":1,"narration":"VAT ALAT NIP TRANSFER TO GTB-Junefirst","date":"2020-05-19T00:00:00","balance":9447},{"id":"6832754","type":"debit","amount":2600,"narration":"ALAT NIP TRANSFER TO GTB-order","date":"2020-05-19T00:00:00","balance":6847},{"id":"6832754","type":"debit","amount":10,"narration":"COMM ALAT NIP TRANSFER TO GTB-order","date":"2020-05-19T00:00:00","balance":6837},{"id":"6832754","type":"credit","amount":0,"narration":"VAT ALAT NIP TRANSFER TO GTB-order","date":"2020-05-19T00:00:00","balance":6836},{"id":"7478159","type":"debit","amount":2000,"narration":"ALAT NIP TRANSFER TO GTB-","date":"2020-05-20T00:00:00","balance":4836},{"id":"7478159","type":"debit","amount":10,"narration":"COMM ALAT NIP TRANSFER TO GTB-","date":"2020-05-20T00:00:00","balance":4826},{"id":"7478159","type":"credit","amount":0,"narration":"VAT ALAT NIP TRANSFER TO GTB-","date":"2020-05-20T00:00:00","balance":4825},{"id":"9904627","type":"credit","amount":7000,"narration":"Wema USSD Transfer from OLAYEMI AFOLARIN OYE","date":"2020-05-27T00:00:00","balance":11825},{"id":"9949826","type":"credit","amount":20000,"narration":"Wema USSD Transfer from BOLU JOHNSON OGUNDOW","date":"2020-05-27T00:00:00","balance":31825}]'